/* Generated By:JavaCC: Do not edit this line. PrismParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PrismParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int COMMENT = 2;
  /** RegularExpression Id. */
  int A = 3;
  /** RegularExpression Id. */
  int AGENT = 4;
  /** RegularExpression Id. */
  int ASYNC = 5;
  /** RegularExpression Id. */
  int AE = 6;
  /** RegularExpression Id. */
  int GS = 7;
  /** RegularExpression Id. */
  int BOOL = 8;
  /** RegularExpression Id. */
  int CLOCK = 9;
  /** RegularExpression Id. */
  int CONST = 10;
  /** RegularExpression Id. */
  int CSG = 11;
  /** RegularExpression Id. */
  int CTMC = 12;
  /** RegularExpression Id. */
  int CTMDP = 13;
  /** RegularExpression Id. */
  int C = 14;
  /** RegularExpression Id. */
  int DISCOUNT = 15;
  /** RegularExpression Id. */
  int DOUBLE = 16;
  /** RegularExpression Id. */
  int DTMC = 17;
  /** RegularExpression Id. */
  int E = 18;
  /** RegularExpression Id. */
  int ENDAGENT = 19;
  /** RegularExpression Id. */
  int ENDENVIRONMENT = 20;
  /** RegularExpression Id. */
  int ENDINIT = 21;
  /** RegularExpression Id. */
  int ENDINVARIANT = 22;
  /** RegularExpression Id. */
  int ENDMODULE = 23;
  /** RegularExpression Id. */
  int ENDPLAYER = 24;
  /** RegularExpression Id. */
  int ENDREWARDS = 25;
  /** RegularExpression Id. */
  int ENDSYSTEM = 26;
  /** RegularExpression Id. */
  int ENDUPDATE = 27;
  /** RegularExpression Id. */
  int ENVIRONMENT = 28;
  /** RegularExpression Id. */
  int FALSE = 29;
  /** RegularExpression Id. */
  int FORMULA = 30;
  /** RegularExpression Id. */
  int FILTER = 31;
  /** RegularExpression Id. */
  int FUNC = 32;
  /** RegularExpression Id. */
  int F = 33;
  /** RegularExpression Id. */
  int Fc = 34;
  /** RegularExpression Id. */
  int F0 = 35;
  /** RegularExpression Id. */
  int GLOBAL = 36;
  /** RegularExpression Id. */
  int G = 37;
  /** RegularExpression Id. */
  int INIT = 38;
  /** RegularExpression Id. */
  int INVARIANT = 39;
  /** RegularExpression Id. */
  int I = 40;
  /** RegularExpression Id. */
  int INT = 41;
  /** RegularExpression Id. */
  int LABEL = 42;
  /** RegularExpression Id. */
  int MAXMAX = 43;
  /** RegularExpression Id. */
  int MAXMIN = 44;
  /** RegularExpression Id. */
  int MAX = 45;
  /** RegularExpression Id. */
  int MDP = 46;
  /** RegularExpression Id. */
  int MINMAX = 47;
  /** RegularExpression Id. */
  int MINMIN = 48;
  /** RegularExpression Id. */
  int MIN = 49;
  /** RegularExpression Id. */
  int MODULE = 50;
  /** RegularExpression Id. */
  int X = 51;
  /** RegularExpression Id. */
  int NONDETERMINISTIC = 52;
  /** RegularExpression Id. */
  int PMAXMAX = 53;
  /** RegularExpression Id. */
  int PMAXMIN = 54;
  /** RegularExpression Id. */
  int PMAX = 55;
  /** RegularExpression Id. */
  int PMINMAX = 56;
  /** RegularExpression Id. */
  int PMINMIN = 57;
  /** RegularExpression Id. */
  int PMIN = 58;
  /** RegularExpression Id. */
  int P = 59;
  /** RegularExpression Id. */
  int PLAYER = 60;
  /** RegularExpression Id. */
  int PROBABILISTIC = 61;
  /** RegularExpression Id. */
  int PROB = 62;
  /** RegularExpression Id. */
  int PTA = 63;
  /** RegularExpression Id. */
  int RATE = 64;
  /** RegularExpression Id. */
  int REWARDS = 65;
  /** RegularExpression Id. */
  int RMAXMAX = 66;
  /** RegularExpression Id. */
  int RMAXMIN = 67;
  /** RegularExpression Id. */
  int RMAX = 68;
  /** RegularExpression Id. */
  int RMINMAX = 69;
  /** RegularExpression Id. */
  int RMINMIN = 70;
  /** RegularExpression Id. */
  int RMIN = 71;
  /** RegularExpression Id. */
  int R = 72;
  /** RegularExpression Id. */
  int NMAX = 73;
  /** RegularExpression Id. */
  int NMIN = 74;
  /** RegularExpression Id. */
  int N = 75;
  /** RegularExpression Id. */
  int S = 76;
  /** RegularExpression Id. */
  int STOCHASTIC = 77;
  /** RegularExpression Id. */
  int STPG = 78;
  /** RegularExpression Id. */
  int SMG = 79;
  /** RegularExpression Id. */
  int SYSTEM = 80;
  /** RegularExpression Id. */
  int TRUE = 81;
  /** RegularExpression Id. */
  int U = 82;
  /** RegularExpression Id. */
  int UPDATE = 83;
  /** RegularExpression Id. */
  int W = 84;
  /** RegularExpression Id. */
  int SMODULE = 85;
  /** RegularExpression Id. */
  int ENDSMODULE = 86;
  /** RegularExpression Id. */
  int SREWARDS = 87;
  /** RegularExpression Id. */
  int ENDSREWARDS = 88;
  /** RegularExpression Id. */
  int NOT = 89;
  /** RegularExpression Id. */
  int AND = 90;
  /** RegularExpression Id. */
  int OR = 91;
  /** RegularExpression Id. */
  int IMPLIES = 92;
  /** RegularExpression Id. */
  int IFF = 93;
  /** RegularExpression Id. */
  int RARROW = 94;
  /** RegularExpression Id. */
  int COLON = 95;
  /** RegularExpression Id. */
  int SEMICOLON = 96;
  /** RegularExpression Id. */
  int COMMA = 97;
  /** RegularExpression Id. */
  int DOTS = 98;
  /** RegularExpression Id. */
  int LPARENTH = 99;
  /** RegularExpression Id. */
  int RPARENTH = 100;
  /** RegularExpression Id. */
  int LBRACKET = 101;
  /** RegularExpression Id. */
  int RBRACKET = 102;
  /** RegularExpression Id. */
  int DLBRACKET = 103;
  /** RegularExpression Id. */
  int DRBRACKET = 104;
  /** RegularExpression Id. */
  int LBRACE = 105;
  /** RegularExpression Id. */
  int RBRACE = 106;
  /** RegularExpression Id. */
  int EQ = 107;
  /** RegularExpression Id. */
  int NE = 108;
  /** RegularExpression Id. */
  int LT = 109;
  /** RegularExpression Id. */
  int GT = 110;
  /** RegularExpression Id. */
  int DLT = 111;
  /** RegularExpression Id. */
  int DGT = 112;
  /** RegularExpression Id. */
  int LE = 113;
  /** RegularExpression Id. */
  int GE = 114;
  /** RegularExpression Id. */
  int PLUS = 115;
  /** RegularExpression Id. */
  int MINUS = 116;
  /** RegularExpression Id. */
  int TIMES = 117;
  /** RegularExpression Id. */
  int DIVIDE = 118;
  /** RegularExpression Id. */
  int MODULUS = 119;
  /** RegularExpression Id. */
  int PRIME = 120;
  /** RegularExpression Id. */
  int RENAME = 121;
  /** RegularExpression Id. */
  int QMARK = 122;
  /** RegularExpression Id. */
  int DQUOTE = 123;
  /** RegularExpression Id. */
  int REG_INT = 124;
  /** RegularExpression Id. */
  int REG_DOUBLE = 125;
  /** RegularExpression Id. */
  int REG_IDENTPRIME = 126;
  /** RegularExpression Id. */
  int REG_IDENT = 127;
  /** RegularExpression Id. */
  int PREPROC = 128;
  /** RegularExpression Id. */
  int LEXICAL_ERROR = 129;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<COMMENT>",
    "\"A\"",
    "\"agent\"",
    "\"asynchronous\"",
    "\"agentEnvironment\"",
    "\"globalSynchronous\"",
    "\"bool\"",
    "\"clock\"",
    "\"const\"",
    "\"csg\"",
    "\"ctmc\"",
    "\"ctmdp\"",
    "\"C\"",
    "\"disc\"",
    "\"double\"",
    "\"dtmc\"",
    "\"E\"",
    "\"endagent\"",
    "\"endenvironment\"",
    "\"endinit\"",
    "\"endinvariant\"",
    "\"endmodule\"",
    "\"endplayer\"",
    "\"endrewards\"",
    "\"endsystem\"",
    "\"endupdate\"",
    "\"environment\"",
    "\"false\"",
    "\"formula\"",
    "\"filter\"",
    "\"func\"",
    "\"F\"",
    "\"Fc\"",
    "\"F0\"",
    "\"global\"",
    "\"G\"",
    "\"init\"",
    "\"invariant\"",
    "\"I\"",
    "\"int\"",
    "\"label\"",
    "\"maxmax\"",
    "\"maxmin\"",
    "\"max\"",
    "\"mdp\"",
    "\"minmax\"",
    "\"minmin\"",
    "\"min\"",
    "\"module\"",
    "\"X\"",
    "\"nondeterministic\"",
    "\"Pmaxmax\"",
    "\"Pmaxmin\"",
    "\"Pmax\"",
    "\"Pminmax\"",
    "\"Pminmin\"",
    "\"Pmin\"",
    "\"P\"",
    "\"player\"",
    "\"probabilistic\"",
    "\"prob\"",
    "\"pta\"",
    "\"rate\"",
    "\"rewards\"",
    "\"Rmaxmax\"",
    "\"Rmaxmin\"",
    "\"Rmax\"",
    "\"Rminmax\"",
    "\"Rminmin\"",
    "\"Rmin\"",
    "\"R\"",
    "\"Nmax\"",
    "\"Nmin\"",
    "\"N\"",
    "\"S\"",
    "\"stochastic\"",
    "\"stpg\"",
    "\"smg\"",
    "\"system\"",
    "\"true\"",
    "\"U\"",
    "\"update\"",
    "\"W\"",
    "\"smodule\"",
    "\"endsmodule\"",
    "\"srewards\"",
    "\"endsrewards\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"=>\"",
    "\"<=>\"",
    "\"->\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"..\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"[[\"",
    "\"]]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<<\"",
    "\">>\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"\\\'\"",
    "\"<-\"",
    "\"?\"",
    "\"\\\"\"",
    "<REG_INT>",
    "<REG_DOUBLE>",
    "<REG_IDENTPRIME>",
    "<REG_IDENT>",
    "<PREPROC>",
    "<LEXICAL_ERROR>",
  };

}
