import sys

rounds = sys.argv[1]
messages = sys.argv[2]

print("asynchronous = {chooseBlock, chooseTransmit}")
print("agentEnvironment = {block_1, block_2, block_3, block_4, transmit_1, transmit_2, transmit_3, transmit_4}")
print("globalSynchronous = {advanceRound}")
print("")
print("agent module Transmitter")
print("\t// 1: Waiting for blockers to declare")
print("\t// 2: Choosing where to transmit")
print("\t// 3: Waiting to transmit")
print("\t// 4: Waiting for next round")
print("\tstateT: [1..4] init 1;")
print("\ttransmitting : [0..4] init 0;")
print("")
print("\t[advanceRound] (stateT=1) -> 1.0:(stateT'=2);")
print("")
print("\t// Choose where to transmit")
print("\t[chooseTransmit] (stateT=2) -> 0.25:(stateT'=3) & (transmitting'=1)")
print("\t\t+ 0.25:(stateT'=3) & (transmitting'=2)")
print("\t\t+ 0.25:(stateT'=3) & (transmitting'=3)")
print("\t\t+ 0.25:(stateT'=3) & (transmitting'=4);")
print("")
print("\t// Choose where to transmit")
print("\t[transmit_1] (stateT=3) -> 1.0:(stateT'=4) & (transmitting'=0);")
print("\t[transmit_2] (stateT=3) -> 1.0:(stateT'=4) & (transmitting'=0);")
print("\t[transmit_3] (stateT=3) -> 1.0:(stateT'=4) & (transmitting'=0);")
print("\t[transmit_4] (stateT=3) -> 1.0:(stateT'=4) & (transmitting'=0);")
print("")
print("\t[advanceRound] (stateT=4) -> 1.0:(stateT'=1);")
print("endmodule")
print("")
print("agent module Blocker")
print("\t// 1: Choosing where to block")
print("\t// 2: Waiting to block")
print("\t// 3: Waiting for transmitters to finish")
print("\t// 4: Waiting for next round")
print("\tstateB: [1..4] init 1;")
print("\tblocking : [0..5] init 0;")
print("")
print("\t// Choose what to block")
print("\t[chooseBlock] (stateB=1) -> 0.25:(stateB'=2) & (blocking'=1)")
print("\t\t+ 0.25:(stateB'=2) & (blocking'=2)")
print("\t\t+ 0.25:(stateB'=2) & (blocking'=3)")
print("\t\t+ 0.25:(stateB'=2) & (blocking'=4);")
print("")
print("\t[block_1] (stateB=2 & blocking=1) -> 1.0:(stateB'=3) & (blocking'=0);")
print("\t[block_2] (stateB=2 & blocking=2) -> 1.0:(stateB'=3) & (blocking'=0);")
print("\t[block_3] (stateB=2 & blocking=3) -> 1.0:(stateB'=3) & (blocking'=0);")
print("\t[block_4] (stateB=2 & blocking=4) -> 1.0:(stateB'=3) & (blocking'=0);")
print("")
print("\t[advanceRound] (stateB=3) -> 1.0:(stateB'=4);")
print("\t[advanceRound] (stateB=4) -> 1.0:(stateB'=1);")
print("endmodule")
print("")
print("environment module Receiver")
print("\t// 1: Blockers declaring intentions")
print("\t// 2: Transmitters transmitting")
print("\t// 3: Message received")
print("\tstateR: [1..3] init 1;")
print("")
print("\treceived: [0..20] init 0;")
print("\troundsPassed: [0..60] init 0;")
print("")
print("\t// Record which channels are blocked")
print("\tblocked1: bool init false;")
print("\tblocked2: bool init false;")
print("\tblocked3: bool init false;")
print("\tblocked4: bool init false;")
print("\t")
print("\t[block_1] (stateR=1) -> 1.0:(blocked1'=true);")
print("\t[block_2] (stateR=1) -> 1.0:(blocked2'=true);")
print("\t[block_3] (stateR=1) -> 1.0:(blocked3'=true);")
print("\t[block_4] (stateR=1) -> 1.0:(blocked4'=true);")
print("")
print("\t[advanceRound] (stateR=1) -> 1.0:(stateR'=2);")
print("")
print("\t[transmit_1] (blocked1 & stateR=2) -> 0.3:(received'=received+1) & (stateR'=3) + 0.7:(received'=received);")
print("\t[transmit_1] (!blocked1 & stateR=2) -> 0.8:(received'=received+1)  & (stateR'=3) + 0.2:(received'=received);")
print("")
print("\t[transmit_2] (blocked2 & stateR=2) -> 0.3:(received'=received+1) & (stateR'=3) + 0.7:(received'=received);")
print("\t[transmit_2] (!blocked2 & stateR=2) -> 0.8:(received'=received+1) & (stateR'=3) + 0.2:(received'=received);")
print("")
print("\t[transmit_3] (blocked3 & stateR=2) -> 0.3:(received'=received+1) & (stateR'=3) + 0.7:(received'=received);")
print("\t[transmit_3] (!blocked3 & stateR=2) -> 0.8:(received'=received+1) & (stateR'=3) + 0.2:(received'=received);")
print("")
print("\t[transmit_4] (blocked4 & stateR=2) -> 0.3:(received'=received+1) & (stateR'=3) + 0.7:(received'=received);")
print("\t[transmit_4] (!blocked4 & stateR=2) -> 0.8:(received'=received+1) & (stateR'=3) + 0.2:(received'=received);")
print("")
print("\t[transmit_1] (stateR=2) -> 1.0:(stateR'=3);")
print("\t[transmit_2] (stateR=2) -> 1.0:(stateR'=3);")
print("\t[transmit_3] (stateR=2) -> 1.0:(stateR'=3);")
print("\t[transmit_4] (stateR=2) -> 1.0:(stateR'=3);")
print("")
print("\t[advanceRound] ((stateR=2 | stateR=3) & received<" + messages + " & roundsPassed<" + rounds + ") ->")
print("\t\t1.0:(stateR'=1) & (blocked1'=false) & (blocked2'=false) & (blocked3'=false) & (blocked4'=false) & (roundsPassed'=roundsPassed+1);")
print("endmodule")
print("")
print("label \"receivedAll\" = received_E=" + messages + ";")
print("label \"roundsFinished\" = roundsPassed_E=" + rounds + ";")